# Generated by Django 4.2.4 on 2023-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DreamScapes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="sound",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="sound_icons/"),
        ),
    ]
