# Generated by Django 4.2.4 on 2023-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DreamScapes", "0002_alter_category_icon_alter_sound_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dreamuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="dreamuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="path/to/default/image.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
