# Generated by Django 4.2.4 on 2023-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DreamScapes", "0003_dreamuser_date_of_birth_alter_dreamuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreamuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
