# Generated by Django 4.2.4 on 2023-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DreamScapes", "0005_remove_dreamuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
