# Generated by Django 4.2.4 on 2023-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DreamScapes", "0006_dreamuser_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sound",
            name="category",
        ),
        migrations.AddField(
            model_name="sound",
            name="categories",
            field=models.ManyToManyField(to="DreamScapes.category"),
        ),
    ]
