# Generated by Django 4.2.4 on 2023-08-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DreamScapes", "0007_remove_sound_category_sound_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
    ]
